<?php

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\Entity\User;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Form\FormBuilder;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Datetime\Element\Datetime;
use Drupal\Core\Site\Settings;
use Drupal\Core\Url;

function gameengine_theme($existing, $type, $theme, $path)
{
	return array(
		'dashboard_page' => array(
			'variables' => array(
				'test' => null
			)
		),
		'login_page' => array(
			'variables' => array(
				'test' => null
			)
		),
		'create_user_page' => array(
			'variables' => array(
				'classList' => null,
			)
		)
	);
}

function gameengine_user_login($account) {
	// Redirect to the /dashboard
	$response = new RedirectResponse("/dashboard");
	$response->send();
	return;
}

/**
 * Return a list of Classes from the DB
 *
 * @return array
 */
function getListOfClasses(){
	$query = \Drupal::database()->query('SELECT uid, class as name FROM thunderfury__classes ORDER BY class ASC');

	$result = $query->fetchAll();

	return $result;
}

function getClientIp() {
	$ipAddress = '';
	if (getenv('HTTP_CLIENT_IP'))
		$ipAddress = getenv('HTTP_CLIENT_IP');
	else if(getenv('HTTP_X_FORWARDED_FOR'))
		$ipAddress = getenv('HTTP_X_FORWARDED_FOR');
	else if(getenv('HTTP_X_FORWARDED'))
		$ipAddress = getenv('HTTP_X_FORWARDED');
	else if(getenv('HTTP_FORWARDED_FOR'))
		$ipAddress = getenv('HTTP_FORWARDED_FOR');
	else if(getenv('HTTP_FORWARDED'))
		$ipAddress = getenv('HTTP_FORWARDED');
	else if(getenv('REMOTE_ADDR'))
		$ipAddress = getenv('REMOTE_ADDR');
	else
		$ipAddress = 'UNKNOWN';
	return $ipAddress;
}

/**
 * Alter form for custom additions.
 *
 * @param array $form
 *   Form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form State.
 * @param string $form_id
 *   Form ID.
 */
function gameengine_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['actions']['newCustomer'] = [
      '#prefix' => '<a class="basic-link padding-left-5" href="/user/create">',
      '#markup' => 'Don\'t have an account?',
      '#suffix' => '</a>',
    ];
  }
}
