<?php

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\Entity\User;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Form\FormBuilder;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Datetime\Element\Datetime;
use Drupal\Core\Site\Settings;
use Drupal\Core\Url;

function gameengine_theme($existing, $type, $theme, $path)
{
	return array(
		'dashboard_page' => array(
			'variables' => array(
				'test' => null
			)
		),
		'login_page' => array(
			'variables' => array(
				'test' => null
			)
		),
		'create_user_page' => array(
			'variables' => array(
				'classList' => null,
			)
		)
	);
}

function gameengine_user_login($account) {
	// Redirect to the /dashboard
	$response = new RedirectResponse("/dashboard");
	$response->send();
	return;
}

/**
 * Implements hook_user_insert().
 */
function gameengine_user_insert(&$edit, $account, $category) {

	$user = User::load($account->uid);
	// generate random number
	$newDisplayName = (string) mt_rand(0,9999999);
	$newDisplayName = str_pad($newDisplayName, 6, "0", STR_PAD_LEFT);
	$user->field_display_name->value = $newDispalyName;

	$user->save();
}

/**
 * Return a list of Classes from the DB
 *
 * @return array
 */
function getListOfClasses(){
	$query = \Drupal::database()->query('SELECT uid, class as name FROM thunderfury__classes ORDER BY class ASC');

	$result = $query->fetchAll();

	return $result;
}

function getClientIp() {
	$ipAddress = '';
	if (getenv('HTTP_CLIENT_IP'))
		$ipAddress = getenv('HTTP_CLIENT_IP');
	else if(getenv('HTTP_X_FORWARDED_FOR'))
		$ipAddress = getenv('HTTP_X_FORWARDED_FOR');
	else if(getenv('HTTP_X_FORWARDED'))
		$ipAddress = getenv('HTTP_X_FORWARDED');
	else if(getenv('HTTP_FORWARDED_FOR'))
		$ipAddress = getenv('HTTP_FORWARDED_FOR');
	else if(getenv('HTTP_FORWARDED'))
		$ipAddress = getenv('HTTP_FORWARDED');
	else if(getenv('REMOTE_ADDR'))
		$ipAddress = getenv('REMOTE_ADDR');
	else
		$ipAddress = 'UNKNOWN';
	return $ipAddress;
}
